"""
Project-wide constants. No magic numbers anywhere else in the codebase.

All numeric thresholds, limits, and fixed values are defined here.
"""

from typing import Final

# --- Population Generation ---
MAX_POPULATION_SIZE = 10_000
MIN_POPULATION_SIZE = 1
DEFAULT_POPULATION_SIZE = 300
DEFAULT_DEEP_PERSONA_COUNT = 30
DEFAULT_SEED = 42
MAX_PERSONA_VALIDATION_RETRIES = 3
POPULATION_ENGINE_VERSION = "0.1.0"
DEMOGRAPHIC_FILTER_OVERSAMPLE_MULTIPLIER = 5
DEMOGRAPHIC_FILTER_MAX_ATTEMPTS = 500
TIER2_KMEANS_N_INIT = 10
MIN_TIER2_SELECTION_SIZE = 1
DATAFRAME_MIN_EXPECTED_COLUMNS = 140

# --- Persona Attributes ---
ATTRIBUTE_MIN = 0.0
ATTRIBUTE_MAX = 1.0
TOTAL_ATTRIBUTE_COUNT = 145

# --- Age Ranges ---
PARENT_AGE_MIN = 22
PARENT_AGE_MAX = 45
CHILD_AGE_MIN = 2
CHILD_AGE_MAX = 14
MIN_PARENT_CHILD_AGE_GAP = 18

# --- City Tiers ---
CITY_TIERS = ("Tier1", "Tier2", "Tier3")

# --- Decision Engine ---
FUNNEL_STAGES = ("need_recognition", "awareness", "consideration", "purchase")
DECISION_OUTCOMES = ("adopt", "reject")
DEFAULT_NEED_RECOGNITION_THRESHOLD = 0.35
DEFAULT_AWARENESS_THRESHOLD = 0.30
DEFAULT_CONSIDERATION_THRESHOLD = 0.40
DEFAULT_PURCHASE_THRESHOLD = 0.45
DEFAULT_DECISION_THRESHOLDS = {
    "need_recognition": DEFAULT_NEED_RECOGNITION_THRESHOLD,
    "awareness": DEFAULT_AWARENESS_THRESHOLD,
    "consideration": DEFAULT_CONSIDERATION_THRESHOLD,
    "purchase": DEFAULT_PURCHASE_THRESHOLD,
}
CALIBRATION_TARGET_ADOPTION_MIN = 0.12
CALIBRATION_TARGET_ADOPTION_MAX = 0.18
CALIBRATION_TARGET_ADOPTION_MIDPOINT = 0.15
CALIBRATION_RESULTS_PATH = "data/results/calibration.json"
CALIBRATION_BINARY_SEARCH_LOW = -0.25
CALIBRATION_BINARY_SEARCH_HIGH = 0.25
DEFAULT_CALIBRATION_MAX_ITERATIONS = 30
DEFAULT_CAUSAL_TOP_N = 8
CAUSAL_HIGH_IMPORTANCE_MULTIPLIER = 2.0
CAUSAL_SEGMENT_LIFT_VARIATION_THRESHOLD = 1.5
CAUSAL_SEGMENT_KEYS = ("city_tier", "income_bracket")

# --- Scenario Configuration ---
SCENARIO_IDS = (
    "nutrimix_2_6",
    "nutrimix_7_14",
    "magnesium_gummies",
    "protein_mix",
)
SCENARIO_MODE_STATIC: Final = "static"
SCENARIO_MODE_TEMPORAL: Final = "temporal"
SEGMENT_IMPACT_ATTRIBUTES = (
    "city_tier",
    "income_bracket",
    "employment_status",
    "child_age_group",
    "education_level",
)
COUNTERFACTUAL_TOP_SEGMENTS = 5

# --- PRD-008 Analysis (segments / barriers) ---
ANALYSIS_SEGMENT_TOP_BARRIER_REASONS = 3
ANALYSIS_STAGE_SUMMARY_TOP_REASONS = 3

INCOME_BRACKET_LOW_MAX_LPA = 8.0
INCOME_BRACKET_MID_MAX_LPA = 15.0
CHILD_AGE_GROUP_EARLY_MAX = 6
CHILD_AGE_GROUP_MIDDLE_MAX = 10

# --- LJ Pass ---
DEFAULT_LJ_PASS_MONTHLY_PRICE_INR = 299.0
DEFAULT_LJ_PASS_DISCOUNT_PERCENT = 15.0
DEFAULT_LJ_PASS_FREE_TRIAL_MONTHS = 1
DEFAULT_LJ_PASS_RETENTION_BOOST = 0.10
DEFAULT_LJ_PASS_CHURN_REDUCTION = 0.20

# --- ReportAgent ---
REPORT_AGENT_MAX_ITERATIONS = 8
REPORT_AGENT_MODEL = "opus"
REPORT_MIN_SECTIONS = 6
REPORT_MAX_TOOL_CALLS = 15

# --- Dashboard ---
DASHBOARD_PAGE_TITLE = "LittleJoys Persona Engine"
DASHBOARD_BRAND_COLORS = {
    "primary": "#FF6B6B",
    "secondary": "#4ECDC4",
    "accent": "#45B7D1",
    "adopt": "#2ECC71",
    "reject": "#E74C3C",
    "neutral": "#95A5A6",
}
DASHBOARD_DEFAULT_POPULATION_PATH = "data/population"
DASHBOARD_DEFAULT_RESULTS_PATH = "data/results"
DASHBOARD_CHART_HEIGHT = 500
DASHBOARD_HEATMAP_COLORSCALE = "RdYlGn"
DASHBOARD_SCATTER_MARKER_SIZE = 6
DASHBOARD_MAX_TIER2_DISPLAY = 30
DASHBOARD_IMPORTANCE_TOP_N = 10
DASHBOARD_WHATIF_POPULATION_SIZE = 120
DASHBOARD_WHATIF_DEEP_COUNT = 12

FUNNEL_THRESHOLD_NEED_RECOGNITION = 0.25
FUNNEL_THRESHOLD_AWARENESS = 0.15
FUNNEL_THRESHOLD_CONSIDERATION = 0.35
FUNNEL_THRESHOLD_PURCHASE = 0.30

FUNNEL_WEIGHT_NEED_HEALTH_ANXIETY = 0.20
FUNNEL_WEIGHT_NEED_NUTRITION_GAP = 0.25
FUNNEL_WEIGHT_NEED_CHILD_PROACTIVITY = 0.20
FUNNEL_WEIGHT_NEED_IMMUNITY = 0.15
FUNNEL_WEIGHT_NEED_GROWTH = 0.15

FUNNEL_AGE_RELEVANCE_OUTSIDE_RANGE = 0.3
FUNNEL_AGE_RELEVANCE_IN_RANGE = 1.0

FUNNEL_BOOST_PEDIATRICIAN_ENDORSEMENT = 0.15
FUNNEL_BOOST_SCHOOL_PARTNERSHIP = 0.20
FUNNEL_BOOST_INFLUENCER_CAMPAIGN = 0.10
FUNNEL_TRUST_SIGNAL_PEDIATRICIAN_TRUST = 0.6
FUNNEL_SCHOOL_COMMUNITY_ENGAGEMENT_THRESHOLD = 0.5
FUNNEL_INFLUENCER_TRUST_THRESHOLD = 0.5

FUNNEL_CONSIDERATION_DIETARY_MISMATCH = 0.5
FUNNEL_CONSIDERATION_DIETARY_MATCH = 1.0
FUNNEL_RISK_UNFAMILIAR_BRAND_WEIGHT = 0.4

FUNNEL_AWARENESS_BASE_FLOOR = 0.15

FUNNEL_CONSIDERATION_WEIGHT_TRUST = 0.30
FUNNEL_CONSIDERATION_WEIGHT_RESEARCH = 0.20
FUNNEL_CONSIDERATION_WEIGHT_CULTURAL = 0.15
FUNNEL_CONSIDERATION_WEIGHT_BRAND = 0.20
FUNNEL_CONSIDERATION_WEIGHT_RISK = 0.15

FUNNEL_PURCHASE_PRICE_RATIO_CAP = 2.0
FUNNEL_PURCHASE_COMBO_CLIP_MAX = 1.0
FUNNEL_PURCHASE_COMBO_CLIP_MIN = 0.0
FUNNEL_CONSIDERATION_TRUST_THRESHOLD = 0.25
FUNNEL_PURCHASE_BARRIER_THRESHOLD = 0.15

DEFAULT_CHANNEL_MIX_INSTAGRAM = 0.34
DEFAULT_CHANNEL_MIX_YOUTUBE = 0.33
DEFAULT_CHANNEL_MIX_WHATSAPP = 0.33

FUNNEL_NON_PRIMARY_SOCIAL_PLATFORM_MATCH = 0.55

REPEAT_HABIT_BASE = 0.3
REPEAT_HABIT_PER_MONTH = 0.1
REPEAT_LJ_PASS_MULTIPLIER = 1.1
REPEAT_CHURN_LJ_PASS_FACTOR = 0.8
REPEAT_SATISFACTION_HISTORY_MONTHS = 3

TEMPORAL_MONTHLY_AWARENESS_INCREMENT = 0.02
TEMPORAL_LJ_PASS_FRACTION_NUMERATOR = 20
TEMPORAL_LJ_PASS_FRACTION_DENOMINATOR = 100
TEMPORAL_WOM_REACH_MIN = 3
TEMPORAL_WOM_REACH_MAX = 5
DEFAULT_WOM_TRANSMISSION_RATE = 0.15

# --- Simulation ---
MAX_SIMULATION_MONTHS = 24
DEFAULT_SIMULATION_MONTHS = 12
WOM_TRANSMISSION_DECAY = 0.85

# --- Auto-Scenario Exploration (Sprint 10) ---
EXPLORER_DEFAULT_VARIANT_COUNT = 100
EXPLORER_MAX_VARIANT_COUNT = 2000
EXPLORER_SWEEP_STEPS = 6
EXPLORER_GRID_MAX_COMBINATIONS = 500
EXPLORER_MISSED_INSIGHT_LIFT_THRESHOLD = 0.05
EXPLORER_MISSED_INSIGHT_MAX_DISPLAY = 10
EXPLORER_SENSITIVITY_MIN_SCORE = 0.02
EXPLORER_PRICE_MIN = 199
EXPLORER_PRICE_MAX = 999
EXPLORER_PRICE_STEP = 100

# --- Correlation Validation ---
CORRELATION_TOLERANCE = 0.15
DISTRIBUTION_P_VALUE_THRESHOLD = 0.05

# --- Gaussian copula / nearest-PSD repair ---
NEAR_PSD_MAX_ITERATIONS = 10
NEAR_PSD_EIGENVALUE_FLOOR = 1e-8
CHOLESKY_DIAGONAL_JITTER = 1e-6

# --- Demographic conditioning (post-copula linear shifts, z-score scaled) ---
DEMOGRAPHIC_Z_SHIFT_SCALE = 0.07
DEMOGRAPHIC_TIER_INDICATOR_SHIFT = 0.06
DEMOGRAPHIC_CHILD_AGE_SHIFT = 0.05
DEMOGRAPHIC_EMPLOYMENT_SHIFT = 0.06
DEMOGRAPHIC_FAMILY_STRUCTURE_SHIFT = 0.06

# --- Conditional rule engine (additive shifts, then clip) ---
CONDITIONAL_SHIFT_TIER3_AUTHORITY_BIAS = 0.10
CONDITIONAL_SHIFT_TIER3_DIGITAL_COMFORT = 0.08
CONDITIONAL_SHIFT_WORKING_MOTHER_TIME_SCARCITY = 0.15
CONDITIONAL_SHIFT_WORKING_MOTHER_WORK_GUILT = 0.10
CONDITIONAL_SHIFT_FIRST_CHILD_ANXIETY = 0.12
CONDITIONAL_SHIFT_JOINT_EXTENDED_FAMILY = 0.15
CONDITIONAL_SHIFT_JOINT_FAMILY_INFLUENCE = 0.12
CONDITIONAL_SHIFT_HIGH_INCOME_BRAND_PREMIUM = 0.10
CONDITIONAL_SHIFT_HIGH_INCOME_PRICE_SENSITIVITY = 0.10

# --- Business thresholds ---
HIGH_INCOME_LPA_THRESHOLD = 20.0
POSTGRADUATE_EDUCATION_LEVELS = frozenset({"masters", "doctorate", "professional"})
YOUNG_CHILD_AGE_LT = 4
OLDER_CHILD_AGE_GTE = 7
OLDEST_CHILD_AGE_GTE_10 = 10

# Child-age conditioning weights (ARCHITECTURE.md §5.2, mapped to youngest_child_age bands)
DEMOGRAPHIC_CHILD_CONDITIONING_HEALTH_ANXIETY_YOUNG = 0.40
DEMOGRAPHIC_CHILD_CONDITIONING_COMPARISON_OLDER = 0.50
DEMOGRAPHIC_CHILD_CONDITIONING_CHILD_TASTE_VETO_OLDER = 0.50
DEMOGRAPHIC_CHILD_CONDITIONING_CHILD_PESTER_OLDER = 0.45
DEMOGRAPHIC_CHILD_CONDITIONING_CHILD_AUTONOMY_OLDEST = 0.55
DEMOGRAPHIC_CHILD_CONDITIONING_SUPPLEMENT_BELIEF_OLDER = -0.20

# --- LLM ---
LLM_CACHE_DIR = "data/.llm_cache"
LLM_MAX_RETRIES = 3
LLM_RETRY_BASE_DELAY = 1.0

# --- Interviews ---
INTERVIEW_LLM_MODEL = "sonnet"
INTERVIEW_MAX_TURNS = 20
INTERVIEW_MAX_CONTEXT_TOKENS = 8_000
INTERVIEW_RESPONSE_MIN_WORDS = 50
INTERVIEW_RESPONSE_MAX_WORDS = 300
INTERVIEW_MAX_BELIEF_STATEMENTS = 8
INTERVIEW_HISTORY_TAIL_TURNS = 6
INTERVIEW_AI_DISCLOSURE_PATTERNS = [
    "as an ai",
    "language model",
    "i don't have feelings",
    "i'm not a real person",
    "i was programmed",
]

# --- Code Coverage ---
MIN_CODE_COVERAGE_PERCENT = 80

# --- Performance Targets ---
STATIC_SIM_MAX_DURATION_SECONDS = 30
TIER2_MAX_DURATION_SECONDS = 600
INTERVIEW_MAX_RESPONSE_SECONDS = 5
