"""
Project-wide constants. No magic numbers anywhere else in the codebase.

All numeric thresholds, limits, and fixed values are defined here.
"""

# --- Population Generation ---
MAX_POPULATION_SIZE = 10_000
MIN_POPULATION_SIZE = 1
DEFAULT_POPULATION_SIZE = 300
DEFAULT_DEEP_PERSONA_COUNT = 30
DEFAULT_SEED = 42

# --- Persona Attributes ---
ATTRIBUTE_MIN = 0.0
ATTRIBUTE_MAX = 1.0
TOTAL_ATTRIBUTE_COUNT = 145

# --- Age Ranges ---
PARENT_AGE_MIN = 22
PARENT_AGE_MAX = 45
CHILD_AGE_MIN = 2
CHILD_AGE_MAX = 14
MIN_PARENT_CHILD_AGE_GAP = 18

# --- City Tiers ---
CITY_TIERS = ("Tier1", "Tier2", "Tier3")

# --- Decision Engine ---
FUNNEL_STAGES = ("need_recognition", "awareness", "consideration", "purchase")
DECISION_OUTCOMES = ("adopt", "reject")

# --- Simulation ---
MAX_SIMULATION_MONTHS = 24
DEFAULT_SIMULATION_MONTHS = 12
WOM_TRANSMISSION_DECAY = 0.85

# --- Correlation Validation ---
CORRELATION_TOLERANCE = 0.15
DISTRIBUTION_P_VALUE_THRESHOLD = 0.05

# --- Gaussian copula / nearest-PSD repair ---
NEAR_PSD_MAX_ITERATIONS = 10
NEAR_PSD_EIGENVALUE_FLOOR = 1e-8
CHOLESKY_DIAGONAL_JITTER = 1e-6

# --- Demographic conditioning (post-copula linear shifts, z-score scaled) ---
DEMOGRAPHIC_Z_SHIFT_SCALE = 0.07
DEMOGRAPHIC_TIER_INDICATOR_SHIFT = 0.06
DEMOGRAPHIC_CHILD_AGE_SHIFT = 0.05
DEMOGRAPHIC_EMPLOYMENT_SHIFT = 0.06
DEMOGRAPHIC_FAMILY_STRUCTURE_SHIFT = 0.06

# --- Conditional rule engine (additive shifts, then clip) ---
CONDITIONAL_SHIFT_TIER3_AUTHORITY_BIAS = 0.10
CONDITIONAL_SHIFT_TIER3_DIGITAL_COMFORT = 0.08
CONDITIONAL_SHIFT_WORKING_MOTHER_TIME_SCARCITY = 0.15
CONDITIONAL_SHIFT_WORKING_MOTHER_WORK_GUILT = 0.10
CONDITIONAL_SHIFT_FIRST_CHILD_ANXIETY = 0.12
CONDITIONAL_SHIFT_JOINT_EXTENDED_FAMILY = 0.15
CONDITIONAL_SHIFT_JOINT_FAMILY_INFLUENCE = 0.12
CONDITIONAL_SHIFT_HIGH_INCOME_BRAND_PREMIUM = 0.10
CONDITIONAL_SHIFT_HIGH_INCOME_PRICE_SENSITIVITY = 0.10

# --- Business thresholds ---
HIGH_INCOME_LPA_THRESHOLD = 20.0
POSTGRADUATE_EDUCATION_LEVELS = frozenset({"masters", "doctorate", "professional"})
YOUNG_CHILD_AGE_LT = 4
OLDER_CHILD_AGE_GTE = 7
OLDEST_CHILD_AGE_GTE_10 = 10

# Child-age conditioning weights (ARCHITECTURE.md §5.2, mapped to youngest_child_age bands)
DEMOGRAPHIC_CHILD_CONDITIONING_HEALTH_ANXIETY_YOUNG = 0.40
DEMOGRAPHIC_CHILD_CONDITIONING_COMPARISON_OLDER = 0.50
DEMOGRAPHIC_CHILD_CONDITIONING_CHILD_TASTE_VETO_OLDER = 0.50
DEMOGRAPHIC_CHILD_CONDITIONING_CHILD_PESTER_OLDER = 0.45
DEMOGRAPHIC_CHILD_CONDITIONING_CHILD_AUTONOMY_OLDEST = 0.55
DEMOGRAPHIC_CHILD_CONDITIONING_SUPPLEMENT_BELIEF_OLDER = -0.20

# --- LLM ---
LLM_CACHE_DIR = "data/.llm_cache"
LLM_MAX_RETRIES = 3
LLM_RETRY_BASE_DELAY = 1.0

# --- Code Coverage ---
MIN_CODE_COVERAGE_PERCENT = 80

# --- Performance Targets ---
STATIC_SIM_MAX_DURATION_SECONDS = 30
TIER2_MAX_DURATION_SECONDS = 600
INTERVIEW_MAX_RESPONSE_SECONDS = 5
